version: '3.4'

services:
  lab02.characters.api:
    image: ${DOCKER_REGISTRY-}lab02.characters.api
    container_name: lab02.characters.api
    build:
      context: .
      dockerfile: Lab02.Characters.API/Dockerfile
    networks:
      - lab2_net

  lab02.mssql_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: lab02_mssql_db
    container_name: lab02.mssql_db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Bazz1nga
    ports:
      - 1433:1433
    networks:
      - lab2_net
networks:
  lab2_net:
    driver: bridge